[package]
name = "unison-fsmonitor"
description = "unison-fsmonitor implementation"
version = "0.1.0"
authors = ["Junfeng Li <autozimu@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
percent-encoding = "1"
failure = "0"
notify = "4"
log = "0"
env_logger = "0"
