name: build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
    - run: nix-shell --run "cargo build --verbose"
    - run: nix-shell --run "cargo test --verbose"
