name: build-and-test

on: [push]

jobs:
  build:

    runs-on: [macOS-10.14]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
