name: build-and-test

on: [push]

jobs:
  build-and-test:
    runs-on: [macOS-10.14]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: install nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: build
      run: nix-shell --run "cargo build --verbose"
    - name: test
      run: nix-shell --run "cargo test --verbose"
