on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - run: cargo build --release --verbose
    - run: cd target/release && tar -cvf unison-fsmonitor.tar.gz unison-fsmonitor
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/unison-fsmonitor.tar.gz
        asset_name: unison-fsmonitor.tar.gz
        asset_content_type: application/gzip
